services:
  nginx:
    image: nginx
volumes:
  example-compose-volume:
     labels:
      - com.packtpub.compose.app=volume-example
  nfsvol:
    driver_opts:
      type: "nfs"
      o: "addr=127.0.0.1,nolock,rw"
      device: ":/data"
